# Generated by Django 5.0.6 on 2024-07-04 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_current_status_product_quatity_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='deleted',
        ),
    ]
