# Generated by Django 5.0.6 on 2024-07-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Vivo', 'Vivo'), ('Xiaomi', 'Xiaomi'), ('Oppo', 'Oppo'), ('Huawei', 'Huawei'), ('realme', 'realme'), ('Lenovo', 'Lenovo'), ('Motorala', 'Motorala'), ('Techno', 'Techno'), ('Sony', 'Sony'), ('Asus', 'Asus'), ('Acer', 'Acer'), ('Dell', 'Dell'), ('HP', 'HP'), ('Samsung', 'Samsung'), ('LG', 'LG'), ('Nokia', 'Nokia'), ('Google', 'Google')], max_length=50),
        ),
    ]
