# Generated by Django 5.0.6 on 2024-07-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_locality_address_address_remove_address_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(choices=[('AnGiang', 'An Giang'), ('BaRiaVungTau', 'Bà Rịa - Vũng Tàu'), ('BacLieu', 'Bạc Liêu'), ('BacGiang', 'Bắc Giang'), ('BacKan', 'Bắc Kạn'), ('BacNinh', 'Bắc Ninh'), ('BenTre', 'Bến Tre'), ('BinhDinh', 'Bình Định'), ('BinhDuong', 'Bình Dương'), ('BinhPhuoc', 'Bình Phước'), ('BinhThuan', 'Bình Thuận'), ('CaMau', 'Cà Mau'), ('CaoBang', 'Cao Bằng'), ('CanTho', 'Cần Thơ'), ('DaNang', 'Đà Nẵng'), ('DakLak', 'Đắk Lắk'), ('DakNong', 'Đắk Nông'), ('DienBien', 'Điện Biên'), ('DongNai', 'Đồng Nai'), ('DongThap', 'Đồng Tháp'), ('GiaLai', 'Gia Lai'), ('HaGiang', 'Hà Giang'), ('HaNam', 'Hà Nam'), ('HaNoi', 'Hà Nội'), ('HaTinh', 'Hà Tĩnh'), ('HaiDuong', 'Hải Dương'), ('HaiPhong', 'Hải Phòng'), ('HauGiang', 'Hậu Giang'), ('HoaBinh', 'Hòa Bình'), ('HungYen', 'Hưng Yên'), ('KhanhHoa', 'Khánh Hòa'), ('KienGiang', 'Kiên Giang'), ('KonTum', 'Kon Tum'), ('LaiChau', 'Lai Châu'), ('LamDong', 'Lâm Đồng'), ('LangSon', 'Lạng Sơn'), ('LaoCai', 'Lào Cai'), ('LongAn', 'Long An'), ('NamDinh', 'Nam Định'), ('NgheAn', 'Nghệ An'), ('NinhBinh', 'Ninh Bình'), ('NinhThuan', 'Ninh Thuận'), ('PhuTho', 'Phú Thọ'), ('PhuYen', 'Phú Yên'), ('QuangBinh', 'Quảng Bình'), ('QuangNam', 'Quảng Nam'), ('QuangNgai', 'Quảng Ngãi'), ('QuangNinh', 'Quảng Ninh'), ('QuangTri', 'Quảng Trị'), ('SocTrang', 'Sóc Trăng'), ('SonLa', 'Sơn La'), ('TayNinh', 'Tây Ninh'), ('ThaiBinh', 'Thái Bình'), ('ThaiNguyen', 'Thái Nguyên'), ('ThanhHoa', 'Thanh Hóa'), ('ThuaThienHue', 'Thừa Thiên Huế'), ('TienGiang', 'Tiền Giang'), ('TPHCM', 'TP Hồ Chí Minh'), ('TraVinh', 'Trà Vinh'), ('TuyenQuang', 'Tuyên Quang'), ('VinhLong', 'Vĩnh Long'), ('VinhPhuc', 'Vĩnh Phúc'), ('YenBai', 'Yên Bái')], max_length=100),
        ),
    ]
