# Generated by Django 5.0.6 on 2024-07-12 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_address_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
