# Generated by Django 5.0.6 on 2024-07-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_order_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_oder',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='order',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selling_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
