# Generated by Django 5.0.6 on 2024-08-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_date_oder_order_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcode',
            name='key',
            field=models.CharField(default='', max_length=5),
        ),
    ]
