export const path = {
    HOME: "/",
    HOMEPAGE: "/home",
    PHONEPAGE: "/phone",
    LAPTOPPAGE: "/laptop",
    TABLETPAGE: "/tablet",
    DETAILPRODUCTPAGE: "/product-detail/:id",
    USERINFOPAGE: "/user-info",
    ADDRESSINFOPAGE: "/address-info",
    RESETPASSPAGE: "/reset-password",
    LOGIN: "/login",
    LOG_OUT: "/logout",
    SYSTEM: "/system",
};

export const LANGUAGES = {
    VI: "vi",
    EN: "en",
};
export const DISCOUNT_CHOICES = [
    { value: 0, label: 0 },
    { value: 10, label: 10 },
    { value: 20, label: 20 },
    { value: 30, label: 30 },
    { value: 40, label: 40 },
    { value: 50, label: 50 },
    { value: 60, label: 60 },
    { value: 70, label: 70 },
    { value: 80, label: 80 },
    { value: 90, label: 90 },
    { value: 100, label: 100 },
];
export const PROVINCE_CHOICES = [
    { value: "", label: "" },
    { value: "AnGiang", label: "An Giang" },
    { value: "BaRiaVungTau", label: "Bà Rịa - Vũng Tàu" },
    { value: "BacLieu", label: "Bạc Liêu" },
    { value: "BacGiang", label: "Bắc Giang" },
    { value: "BacKan", label: "Bắc Kạn" },
    { value: "BacNinh", label: "Bắc Ninh" },
    { value: "BenTre", label: "Bến Tre" },
    { value: "BinhDinh", label: "Bình Định" },
    { value: "BinhDuong", label: "Bình Dương" },
    { value: "BinhPhuoc", label: "Bình Phước" },
    { value: "BinhThuan", label: "Bình Thuận" },
    { value: "CaMau", label: "Cà Mau" },
    { value: "CaoBang", label: "Cao Bằng" },
    { value: "CanTho", label: "Cần Thơ" },
    { value: "DaNang", label: "Đà Nẵng" },
    { value: "DakLak", label: "Đắk Lắk" },
    { value: "DakNong", label: "Đắk Nông" },
    { value: "DienBien", label: "Điện Biên" },
    { value: "DongNai", label: "Đồng Nai" },
    { value: "DongThap", label: "Đồng Tháp" },
    { value: "GiaLai", label: "Gia Lai" },
    { value: "HaGiang", label: "Hà Giang" },
    { value: "HaNam", label: "Hà Nam" },
    { value: "HaNoi", label: "Hà Nội" },
    { value: "HaTinh", label: "Hà Tĩnh" },
    { value: "HaiDuong", label: "Hải Dương" },
    { value: "HaiPhong", label: "Hải Phòng" },
    { value: "HauGiang", label: "Hậu Giang" },
    { value: "HoaBinh", label: "Hòa Bình" },
    { value: "HungYen", label: "Hưng Yên" },
    { value: "KhanhHoa", label: "Khánh Hòa" },
    { value: "KienGiang", label: "Kiên Giang" },
    { value: "KonTum", label: "Kon Tum" },
    { value: "LaiChau", label: "Lai Châu" },
    { value: "LamDong", label: "Lâm Đồng" },
    { value: "LangSon", label: "Lạng Sơn" },
    { value: "LaoCai", label: "Lào Cai" },
    { value: "LongAn", label: "Long An" },
    { value: "NamDinh", label: "Nam Định" },
    { value: "NgheAn", label: "Nghệ An" },
    { value: "NinhBinh", label: "Ninh Bình" },
    { value: "NinhThuan", label: "Ninh Thuận" },
    { value: "PhuTho", label: "Phú Thọ" },
    { value: "PhuYen", label: "Phú Yên" },
    { value: "QuangBinh", label: "Quảng Bình" },
    { value: "QuangNam", label: "Quảng Nam" },
    { value: "QuangNgai", label: "Quảng Ngãi" },
    { value: "QuangNinh", label: "Quảng Ninh" },
    { value: "QuangTri", label: "Quảng Trị" },
    { value: "SocTrang", label: "Sóc Trăng" },
    { value: "SonLa", label: "Sơn La" },
    { value: "TayNinh", label: "Tây Ninh" },
    { value: "ThaiBinh", label: "Thái Bình" },
    { value: "ThaiNguyen", label: "Thái Nguyên" },
    { value: "ThanhHoa", label: "Thanh Hóa" },
    { value: "ThuaThienHue", label: "Thừa Thiên Huế" },
    { value: "TienGiang", label: "Tiền Giang" },
    { value: "TPHCM", label: "TP Hồ Chí Minh" },
    { value: "TraVinh", label: "Trà Vinh" },
    { value: "TuyenQuang", label: "Tuyên Quang" },
    { value: "VinhLong", label: "Vĩnh Long" },
    { value: "VinhPhuc", label: "Vĩnh Phúc" },
    { value: "YenBai", label: "Yên Bái" },
];
export const manageActions = {
    ADD: "ADD",
    EDIT: "EDIT",
    DELETE: "DELETE",
};

export const dateFormat = {
    SEND_TO_SERVER: "DD/MM/YYYY",
};

export const YesNoObj = {
    YES: "Y",
    NO: "N",
};
